<?php
/**
 * @licence@
 */
/* @var $this Balticode_DpdLT_Block_Order_Courier */
?>
<div class="shipment_info">
    <label for="Po_parcel_qty"><input type="text" name="Po_parcel_qty" id="Po_parcel_qty" value="<?php echo $this->getParcelQty(); ?>"
                                      class="validate-not-negative-number validate-digits"/><?php echo $this->__('Parcels (≤ 31,5kg)'); ?></label>
    <label for="Po_pallet_qty"><input type="text" name="Po_pallet_qty" id="Po_pallet_qty" value="<?php echo $this->getPalletQty(); ?>"
                                      class="validate-not-negative-number validate-digits"/><?php echo $this->__('Pallets'); ?></label>
</div>
<div class="shipment_comment">
    <textarea name="Po_remark" id="Po_remark" cols="40" rows="2" title="<?php echo $this->__('Comment to courier');?>"></textarea>
</div>
<input type="hidden" name="order_ids" id="balticode_dpdlt_order_ids" value=""/>